openapi: 3.2.0
info:
  title: Getty Images Asset Licensing API
  version: '3'
security:
- Api-Key: []
- OAuth2: []
tags:
- name: AssetLicensing
paths:
  /v3/asset-licensing/{assetId}:
    post:
      tags:
      - AssetLicensing
      summary: Endpoint for acquiring extended licenses with iStock credits for an asset
      parameters:
      - name: Accept-Language
        in: header
        description: 'Provide a header to specify the language of result values. Supported values: cs (iStock only), de, en-GB, en-US, es, fi (iStock only), fr, hu (iStock only), id (iStock only), it, ja, ko (creative assets only), nl, pl (creative assets only), pt-BR, pt-PT, ro (iStock only), ru (creative assets only), sv, th (iStock only), tr, uk (iStock only), vi (iStock only), zh-HK (creative assets only).'
        schema:
          type: string
          description: 'Provide a header to specify the language of result values. Supported values: cs (iStock only), de, en-GB, en-US, es, fi (iStock only), fr, hu (iStock only), id (iStock only), it, ja, ko (creative assets only), nl, pl (creative assets only), pt-BR, pt-PT, ro (iStock only), ru (creative assets only), sv, th (iStock only), tr, uk (iStock only), vi (iStock only), zh-HK (creative assets only).'
      - name: assetId
        in: path
        description: Getty Images assetId - examples 520621493, 112301284
        required: true
        schema:
          type: string
      requestBody:
        description: "Structure that specifies an array of LicenseTypes (multiseat, unlimited, resale, indemnification) to acquire,\n            and whether or not to use Team Credits. Authenticated User must have access to Team Credits if UseTeamCredits is set to \"true\"."
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.AssetLicensing.AcquireAssetLicensesRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.AssetLicensing.AssetLicensingResponse'
        '401':
          description: AuthorizationTokenRequired
        '400':
          description: InvalidRequestParameters
        '402':
          description: NotEnoughCreditsForPurchase
        '404':
          description: StandardLicenseNotFound
      operationId: postV3AssetLicensingByAssetId
      x-operation-id-source: derived
components:
  schemas:
    GettyImages.Services.Connect.Public.Controllers.AssetLicensing.ExtendedLicenses:
      enum:
      - multiseat
      - unlimited
      - resale
      - indemnification
      type: string
    GettyImages.Services.Connect.Public.Controllers.AssetLicensing.AssetLicensingResponse:
      type: object
      properties:
        credits_used:
          type: integer
          format: int32
        acquired_licenses:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.AssetLicensing.ExtendedLicenses'
      additionalProperties: false
    GettyImages.Services.Connect.Public.Controllers.AssetLicensing.AcquireAssetLicensesRequest:
      required:
      - extended_licenses
      type: object
      properties:
        extended_licenses:
          type: array
          items:
            $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.AssetLicensing.ExtendedLicenses'
        use_team_credits:
          type: boolean
          description: Defaults to false.
      additionalProperties: false
  securitySchemes:
    Api-Key:
      type: apiKey
      name: Api-Key
      in: header
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: https://authentication.gettyimages.com/oauth2/token
          refreshUrl: https://authentication.gettyimages.com/oauth2/token
          scopes: {}
        clientCredentials:
          tokenUrl: https://authentication.gettyimages.com/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://authentication.gettyimages.com/oauth2/auth
          tokenUrl: https://authentication.gettyimages.com/oauth2/token
          refreshUrl: https://authentication.gettyimages.com/oauth2/token
          scopes: {}
