openapi: 3.2.0
info:
  title: Getty Images Affiliate Search API
  version: '3'
security:
- Api-Key: []
- OAuth2: []
tags:
- name: AffiliateSearch
paths:
  /v3/affiliates/search/images:
    get:
      tags:
      - AffiliateSearch
      summary: Get affiliates search images
      parameters:
      - name: Accept-Language
        in: header
        description: 'Provide a header to specify the language of result values. Supported values: cs (iStock only), de, en-GB, en-US, es, fi (iStock only), fr, hu (iStock only), id (iStock only), it, ja, ko (creative assets only), nl, pl (creative assets only), pt-BR, pt-PT, ro (iStock only), ru (creative assets only), sv, th (iStock only), tr, uk (iStock only), vi (iStock only), zh-HK (creative assets only).'
        schema:
          type: string
          description: 'Provide a header to specify the language of result values. Supported values: cs (iStock only), de, en-GB, en-US, es, fi (iStock only), fr, hu (iStock only), id (iStock only), it, ja, ko (creative assets only), nl, pl (creative assets only), pt-BR, pt-PT, ro (iStock only), ru (creative assets only), sv, th (iStock only), tr, uk (iStock only), vi (iStock only), zh-HK (creative assets only).'
      - name: GI-Country-Code
        in: header
        description: Receive regionally relevant search results based on the value specified. Accepts only ISO Alpha-3 country codes. The Countries operation can be used to retrieve the codes.
        schema:
          type: string
          description: Use of this parameter requires configuration changes to your API key. Please contact your sales representative to learn more.
      - name: phrase
        in: query
        description: Search images using a search phrase.
        schema:
          type: string
      - name: style
        in: query
        description: Filter based on graphical style of the image.
        schema:
          $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateSearchStyle'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateImageSearchResponse'
      x-summary-source: derived
      operationId: getV3AffiliatesSearchImages
      x-operation-id-source: derived
  /v3/affiliates/search/videos:
    get:
      tags:
      - AffiliateSearch
      parameters:
      - name: Accept-Language
        in: header
        description: 'Provide a header to specify the language of result values. Supported values: cs (iStock only), de, en-GB, en-US, es, fi (iStock only), fr, hu (iStock only), id (iStock only), it, ja, ko (creative assets only), nl, pl (creative assets only), pt-BR, pt-PT, ro (iStock only), ru (creative assets only), sv, th (iStock only), tr, uk (iStock only), vi (iStock only), zh-HK (creative assets only).'
        schema:
          type: string
          description: 'Provide a header to specify the language of result values. Supported values: cs (iStock only), de, en-GB, en-US, es, fi (iStock only), fr, hu (iStock only), id (iStock only), it, ja, ko (creative assets only), nl, pl (creative assets only), pt-BR, pt-PT, ro (iStock only), ru (creative assets only), sv, th (iStock only), tr, uk (iStock only), vi (iStock only), zh-HK (creative assets only).'
      - name: GI-Country-Code
        in: header
        description: Receive regionally relevant search results based on the value specified. Accepts only ISO Alpha-3 country codes. The Countries operation can be used to retrieve the codes.
        schema:
          type: string
          description: Use of this parameter requires configuration changes to your API key. Please contact your sales representative to learn more.
      - name: phrase
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateVideoSearchResponse'
      summary: Get affiliates search videos
      x-summary-source: derived
      operationId: getV3AffiliatesSearchVideos
      x-operation-id-source: derived
components:
  schemas:
    GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateImage:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        caption:
          type:
          - string
          - 'null'
        preview_urls:
          $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateImageUrls'
        destination_url:
          type:
          - string
          - 'null'
      additionalProperties: false
    GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateImageUrls:
      type: object
      properties:
        small:
          type:
          - string
          - 'null'
        small_height:
          type: integer
          format: int32
        small_width:
          type: integer
          format: int32
        medium:
          type:
          - string
          - 'null'
        medium_height:
          type: integer
          format: int32
        medium_width:
          type: integer
          format: int32
        large:
          type:
          - string
          - 'null'
        large_height:
          type: integer
          format: int32
        large_width:
          type: integer
          format: int32
      additionalProperties: false
    GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateVideoSearchResponse:
      type: object
      properties:
        videos:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateVideo'
        auto_corrections:
          $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Models.Search.AutoCorrections'
      additionalProperties: false
    GettyImages.Services.Connect.Public.Models.Search.AutoCorrections:
      type: object
      properties:
        phrase:
          type:
          - string
          - 'null'
      additionalProperties: false
    GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateSearchStyle:
      enum:
      - photography
      - vector
      type: string
      description: Specifies the graphical style of images desired.
    GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateVideoUrls:
      type: object
      properties:
        small_still:
          type:
          - string
          - 'null'
        medium_still:
          type:
          - string
          - 'null'
        large_still:
          type:
          - string
          - 'null'
        small_motion:
          type:
          - string
          - 'null'
        large_motion:
          type:
          - string
          - 'null'
      additionalProperties: false
    GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateVideo:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        caption:
          type:
          - string
          - 'null'
        preview_urls:
          $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateVideoUrls'
        destination_url:
          type:
          - string
          - 'null'
        clip_length:
          type:
          - string
          - 'null'
      additionalProperties: false
    GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateImageSearchResponse:
      type: object
      properties:
        images:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Controllers.Affiliate.AffiliateImage'
        auto_corrections:
          $ref: '#/components/schemas/GettyImages.Services.Connect.Public.Models.Search.AutoCorrections'
      additionalProperties: false
  securitySchemes:
    Api-Key:
      type: apiKey
      name: Api-Key
      in: header
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: https://authentication.gettyimages.com/oauth2/token
          refreshUrl: https://authentication.gettyimages.com/oauth2/token
          scopes: {}
        clientCredentials:
          tokenUrl: https://authentication.gettyimages.com/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://authentication.gettyimages.com/oauth2/auth
          tokenUrl: https://authentication.gettyimages.com/oauth2/token
          refreshUrl: https://authentication.gettyimages.com/oauth2/token
          scopes: {}
